"""Componentes interactivos compartidos para los materiales del curso."""

from .exercise_feedback import (
    CheckResult,
    Criterion,
    ExerciseAttempt,
    ExerciseRuntime,
    FeedbackCoach,
    FeedbackContent,
    FeedbackSession,
    FeedbackTools,
    NameSnapshot,
    PredicateSpec,
    capture_names,
    check,
    criterion,
    display_coach,
    evaluate_names,
    evaluate_snapshot,
    load_feedback,
    load_feedback_content,
    setup_feedback,
)

__all__ = [
    "CheckResult",
    "Criterion",
    "ExerciseAttempt",
    "ExerciseRuntime",
    "FeedbackCoach",
    "FeedbackContent",
    "FeedbackSession",
    "FeedbackTools",
    "NameSnapshot",
    "PredicateSpec",
    "capture_names",
    "check",
    "criterion",
    "display_coach",
    "evaluate_names",
    "evaluate_snapshot",
    "load_feedback_content",
    "load_feedback",
    "setup_feedback",
]
